apiVersion: apps/v1
kind: Deployment
metadata:
  name: memorycard-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memorycard-dev
  template:
    metadata:
      labels:
        app: memorycard-dev
    spec:
      containers:
      - name: run
        image: local/memorycard_docker_image:0.0.2
        env:
        - name: DB_HOST
          value: postgres:5432
        resources:
          limits:
            memory: "256Mi"
            cpu: 1
          requests:
            memory: "128Mi"
            cpu: 0.5
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 20"]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: memorycard-dev
  name: memorycard-dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: memorycard-dev
  sessionAffinity: None
  type: ClusterIP
